/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Backpack: typeof import('./src/components/Backpack.vue')['default']
    Battle: typeof import('./src/components/Battle.vue')['default']
    BattleEnd: typeof import('./src/components/BattleEnd.vue')['default']
    BattleStart: typeof import('./src/components/BattleStart.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChooseCharacter: typeof import('./src/components/ChooseCharacter.vue')['default']
    Detail: typeof import('./src/components/Detail.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ItemComponent: typeof import('./src/components/ItemComponent.vue')['default']
    Mumble: typeof import('./src/components/Mumble.vue')['default']
    PlayerStatus: typeof import('./src/components/PlayerStatus.vue')['default']
    Rank: typeof import('./src/components/Rank.vue')['default']
    Rest: typeof import('./src/components/Rest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./src/components/Shop.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}
