export const StoreAction = {
    changeGameState: 'changeGameState',
    selectCharacter: 'selectCharacter',
    generateEnemy: 'generateEnemy',
    switchSpinner: 'switchSpinner',
    playerMumble: 'playerMumble',
    enemyMumble: 'enemyMumble',
    deduction: 'deduction',
    heal: 'heal',
    updatePlayer: 'updatePlayer',
    switchRank: 'switchRank',
    switchBackpack: 'switchBackpack',
    switchShop: 'switchShop',
    updateShop: 'updateShop',
    fetchData: 'fetchData',
    updateData: 'updateData',
}